--- 
title       : Household Income Analysis Application
subtitle    : How does your income stack up?
author      : Blane McCarthy
job         : Data Science Student
framework   : io2012   # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
logo        : income.png

--- 

## Household Income Analysis

Are you earning the income that you deserve? 

How much more could you earn with a higher level of education?  

What if you changed career fields?  

What impact would that have on your income?

This simple yet effective app will answer these questions and more.


---  .class: class1, bg: url(assets/img/income.png), #id: id1

## Household Income Analysis

Compare your household income with those of a broad market basket sample of incomes.  

This app will allow you to see how you are doing based upon the following criteria:

1. Gender
2. Education Level
3. Occupation Category

--- {class: class1, bg: url(assets/img/income.png), id: id1}

## Household Income Analysis

 For an incredibly low price you get not only the impressive flexibility previously described,

 but you also get data from a broad market basket of samples.
 
 The data comes from the prestigious organization, 
 
 Impact Resources, Inc., of Columbus, Ohio.
 
 https://bmcarthy.shinyapps.io/IncomeAnalysis/

--- class: class1, bg: bg, id: id1

## Household Income Analysis 

Here is a sample of the results you will receive from the application. 

```{r, echo=FALSE}
library(ElemStatLearn)

data("marketing")

submarket <- subset(marketing, Sex == 1 & Edu == 3 & Occupation == 3)

hist(submarket$Income, breaks = 100, freq = FALSE, col='lightblue', 
     main = NULL, xlim=c(0, 10), xlab=NULL)
     title(main='Histogram Showing Your Household Income, (Red Bar), Relative 
 to Those With Same Gender, Occupation, and Education Level',
     cex.sub = .8, 
     sub = "Income Rating
     1. < $10000, 2. $10000 - $14999, 3. $15000 - $19999, 4. $20000 - $24999, 
     5. $25000 - $29999, 6. $30000 - $39999, 7. $40000 - $49999, 8. $50000 - $74999, 9. > $75000")
     lines(c(3, 3), c(0, 1.8),col="red",lwd=3)
     mu <- round(mean(submarket$Income),0)
     text(9.0, 1, paste("Average\nIncome  \n Rating = \n", mu))

```






